### PR TITLE
Improve oauth retry

### PR DESCRIPTION
**Pull request by tmckayus**
* Only retry if an oauth exception contains "SSL certificate problem"
* Only retry if both cert bundles exist
* Remove the state change of the instance variable on success and
  just always retry, since it's unclear how this routine is being
  called by jupyterhub (it might not be threadsafe)
* Modified the error message to say what failed and what the retry will be

### CODE REVIEW

**Comment by tmckayus** [comment]
It's difficult to test the failure paths without doing whitebox testing unless you can control the certificates that are used for the oauth endpoint and the certificate bundle that is injected into the pod at /run/secrets/kubernetes.io/serviceaccount/ca.crt

On recent OpenShift Dedicated clusters, login should just work with no retry in the logs
On clusters with self-signed oauth endpoints, login should just work with no retry in the logs

On a cluster with a self-signed oauth endpoint, I ran jupyterhub from within the pod and changed the default in openshift.py to try the system ca bundle first, and it generated the following log:

```
[E 2021-07-02 15:34:14.430 JupyterHub oauth2:376] Error fetching 599 POST https://oauth-openshift.apps.somecluster.com/oauth/token: HTTP 599: SSL certificate problem: self signed certificate in certificate chain
[I 2021-07-02 15:34:14.430 JupyterHub openshift:138] Oauth token request failed with /etc/pki/tls/cert.pem, retrying with /run/secrets/kubernetes.io/serviceaccount/ca.crt
[I 2021-07-02 15:34:14.598 JupyterHub base:762] User logged in: tmckay
```

The log will be repeated on each login.  If you would like to reproduce this test:

0) Build a jupyterhub image with this change in oauthenticator
1) Make the command for a jupyterhub podspec be a no-op such as the following
```
      - args:
        - while true; do echo looping...; sleep 5; done
        command:
        - /bin/sh
        - -c
        - --
```
2) rsh into the running jupyterhub pod
3) edit /opt/app-root/lib/python3.8/site-packages/oauthenticator/openshift.py 
4) initialize use_ca_certs_for_token_request to False
5) run jupyterhub from the pod commandline with "start-jupyterhub.sh"
6) connect to jupyterhub as normal
7) watch the logs

**Comment by tmckayus** [comment]
Therre is a prebuilt image with this fix at quay.io/tmckayus/jupyterhub-img:testretry

Build configs to make your own image can be found on https://github.com/opendatahub-io/oauthenticator/pull/3 (the original fix)

**Comment by vpavlin** [comment]
Seems like for whatever reason I cannot get the logic to execute with warning. The code looks good though and I can login with setting either True or False for use_ca_certs_for_token_request.

LGTM, but would be good if someone else can test/review it as well

**Review by vpavlin — APPROVED** [review]

**Comment by tmckayus** [comment]
@vpavlin another way to do whitebox testing on this is to insert a raise CurlError(1, "whatever") inside the exception block and force the exception. This will at least prove that the retry code itself works, and the message is logged.

**Pull request merged**
